# Generated by Django 4.1.7 on 2023-03-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tg_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='Id чата в ТГ')),
                ('username', models.CharField(max_length=250, unique=True, verbose_name='Username в ТГ')),
                ('first_name', models.CharField(blank=True, max_length=250, verbose_name='Имя в ТГ')),
                ('last_name', models.CharField(blank=True, max_length=250, verbose_name='Фамилия в ТГ')),
                ('tokens_used', models.IntegerField(null=True, verbose_name='Общее количество токенов')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
