# Generated by Django 4.1.7 on 2023-03-11 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField(verbose_name='Id сообщения пользователя')),
                ('date', models.FloatField(verbose_name='Время сообщения')),
                ('text', models.TextField(blank=True, verbose_name='Текст сообщения')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sent_msgs', to='payments.tg_user', verbose_name='автор сообщения')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='GPT_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=250, unique=True, verbose_name='Id сообщения от GPT чата')),
                ('date', models.FloatField(verbose_name='Время сообщения от GPT чата')),
                ('gpt_model', models.CharField(max_length=250, verbose_name='Модель GPT чата')),
                ('total_tokens', models.IntegerField(verbose_name='Общее количество токенов')),
                ('text', models.TextField(blank=True, verbose_name='Текст сообщения от GPT чата')),
                ('user_message', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='gpt_response', to='payments.user_message', verbose_name='Запрос от пользователя')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
