# Generated by Django 4.1.7 on 2023-03-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_user_message_gpt_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название тарифа')),
                ('description', models.TextField(verbose_name='Описание тарифа')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
