# Generated by Django 4.1.7 on 2023-03-11 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_tariff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_payment_id', models.TextField(verbose_name='Id оплаты в ТГ')),
                ('bank_payment_id', models.TextField(verbose_name='Id оплаты в банке')),
                ('date', models.FloatField(verbose_name='Дата оплаты')),
                ('amount', models.FloatField(null=True, verbose_name='Сумма оплаты')),
                ('currency', models.CharField(blank=True, max_length=10, verbose_name='Валюта оплаты')),
                ('tariff', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.tariff')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.tg_user')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
