# Generated by Django 4.1.7 on 2023-03-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gpt_message',
            options={'ordering': ['date'], 'verbose_name': 'Ответ GPT бота', 'verbose_name_plural': 'Ответы GPT бота'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['date'], 'verbose_name': 'Оплата', 'verbose_name_plural': 'Оплаты'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ['name'], 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterModelOptions(
            name='tg_user',
            options={'ordering': ['username'], 'verbose_name': 'Пользователь ТГ', 'verbose_name_plural': 'Пользователи ТГ'},
        ),
        migrations.AlterModelOptions(
            name='user_message',
            options={'ordering': ['date'], 'verbose_name': 'Запрос пользователей', 'verbose_name_plural': 'Запросы пользователей'},
        ),
        migrations.AddField(
            model_name='tg_user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Член команды'),
        ),
    ]
