# Generated by Django 4.1.7 on 2023-03-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_gpt_message_date_alter_user_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpt_message',
            name='date',
            field=models.DateTimeField(verbose_name='Время сообщения от GPT чата'),
        ),
        migrations.AlterField(
            model_name='user_message',
            name='date',
            field=models.DateTimeField(verbose_name='Время сообщения'),
        ),
    ]
