# Generated by Django 4.1.7 on 2023-03-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bank_payment_id',
            field=models.CharField(max_length=255, verbose_name='Id оплаты в банке'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tg_payment_id',
            field=models.CharField(max_length=255, verbose_name='Id оплаты в ТГ'),
        ),
    ]
