# Generated by Django 4.1.7 on 2023-04-01 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_payment_bank_payment_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GPT_message',
            new_name='GPTMessage',
        ),
        migrations.RenameModel(
            old_name='Tg_user',
            new_name='TgUser',
        ),
        migrations.RenameModel(
            old_name='User_message',
            new_name='UserMessage',
        ),
    ]
